name: dach-trier

services:
  tunnel:
    image: cloudflare/cloudflared:2026.3.0
    restart: unless-stopped
    command: tunnel --no-autoupdate run

    env_file:
      - ./env/cloudflared.env

    networks:
      - web

  public-server:
    image: ghcr.io/dach-trier/public-server:v1.0.0
    restart: unless-stopped

    environment:
      PORT: "80"
      GOOGLE_APPLICATION_CREDENTIALS: "/secrets/public-sa.json"
    volumes:
      - ./secrets/public-sa.json:/secrets/public-sa.json

    networks:
      - web

  portal-database:
    image: postgres:18.3-alpine3.22
    restart: unless-stopped

    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       portal

    healthcheck:
      test: ["CMD-SHELL", "psql -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1'"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

    volumes:
      - ./volumes/portal_database:/var/lib/postgresql/18/docker

    networks:
      - web

  portal-migration:
    image: ghcr.io/dach-trier/portal-migration:v0.1.0
    restart: no

    depends_on:
      portal-database:
        condition: service_healthy

    environment:
      DB_HOST: "portal-database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_NAME: "portal"

    networks:
      - web

  portal-server:
    image: ghcr.io/dach-trier/portal-server:v0.1.0
    restart: unless-stopped

    depends_on:
      portal-database:
        condition: service_healthy

      portal-migration:
        condition: service_completed_successfully
        
    environment:
      PORT: "80"
      MODE: "release"

      DB_HOST: "portal-database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_NAME: "portal"

    networks:
      - web

networks:
  web:
    driver: bridge
